Dataset:
  Calibration:
    cx: 315.59352
    cy: 237.756098
    depth_scale: 5000.0
    distorted: true
    fx: 542.822841
    fy: 542.57687
    height: 480
    k1: 0.039903
    k2: -0.099343
    k3: 0.0
    p1: -0.00073
    p2: -0.000144
    width: 640
  adaptive_pointsize: true
  bound:
  - - -8.0
    - -8.5
    - -7.0
  - - 8.5
    - 8.5
    - 8.0
  dataset_path: datasets/bonn/rgbd_bonn_balloon
  eval_rendering: false
  pcd_downsample: 128
  pcd_downsample_init: 32
  point_size: 0.01
  sensor_type: depth
  type: tum
Results:
  eval_rendering: true
  save_dir: results
  save_results: false
  save_trj: true
  save_trj_kf_intv: 5
  use_gui: false
  use_wandb: false
Training:
  alpha: 0.9
  dystart: 32
  edge_threshold: 1.1
  flow_loss: 3.0
  gaussian_extent: 1.0
  gaussian_reset: 2001
  gaussian_th: 0.7
  gaussian_update_every: 150
  gaussian_update_offset: 50
  init_gaussian_extent: 30
  init_gaussian_reset: 500
  init_gaussian_th: 0.005
  init_gaussian_update: 100
  init_itr_num: 1050
  kf_cutoff: 0.3
  kf_interval: 5
  kf_min_translation: 0.05
  kf_overlap: 0.9
  kf_translation: 0.08
  lr:
    cam_rot_delta: 0.003
    cam_trans_delta: 0.001
  mapping_itr_num: 50
  mask_loss: 0.01
  offset_loss: 1.0
  pose_window: 3
  prune_mode: slam
  rgb_boundary_threshold: 0.01
  single_thread: true
  size_threshold: 20
  spherical_harmonics: false
  tracking_itr_num: 200
  window_size: 8
model_params:
  data_device: cuda
  depth_check: true
  dynamic_model: offset
  flow_cam: true
  flow_mask: true
  flow_offset: true
  insertion: true
  model_path: ''
  resolution: -1
  sd: true
  sh_degree: 0
  source_path: ''
  use_gmm: true
  use_gmm_rot: true
  use_knn: true
  white_background: false
opt_params:
  deformation_lr_delay_mult: 0.01
  deformation_lr_final: 1.6e-05
  deformation_lr_init: 0.00016
  densification_interval: 100
  densify_from_iter: 500
  densify_grad_threshold: 0.0002
  densify_until_iter: 15000
  feature_lr: 0.0025
  grid_lr_final: 0.00016
  grid_lr_init: 0.0016
  iterations: 30000
  lambda_dssim: 0.2
  opacity_lr: 0.05
  opacity_reset_interval: 3000
  percent_dense: 0.01
  position_lr_delay_mult: 0.01
  position_lr_final: 1.6e-06
  position_lr_init: 0.00016
  position_lr_max_steps: 30000
  rotation_lr: 0.001
  scaling_lr: 0.001
  trbfc_lr: 0.0001
  trbfs_lr: 0.04
pipeline_params:
  compute_cov3D_python: false
  convert_SHs_python: false
yolo: true
